# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - phystrack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_88e3ae026e1249428fa9d590b928fab7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d602b01fcefb40a4973620a2c54eb028 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_88e3ae026e1249428fa9d590b928fab7 }}/twa-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'phystrack'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_954aa6fbd5324250b557505ad2f89c0b }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_88e3ae026e1249428fa9d590b928fab7 }}/twa-image:${{ github.sha }}'